### ISSUE TITLE
Adding tabs to an App with sub-tabs might break on V12

### ISSUE THREAD

**Issue by mclemente** [theripper93/injectConfig#2]
The Scene Configuration app's last tab has its own sub-tabs, which break when adding your own tab due to the `html.find(".tab").last()` here:
https://github.com/theripper93/injectConfig/blob/0e611485688f684afef6ce5e5a0f9ced9ac73310/injectConfig.js#L17

For my use-case, I've fixed it by changing the line to use `html.find(".tab[data-group='main']").last()`, but I am not sure if this works for every case, so I didn't make a PR.

How to reproduce:
```js
Hooks.on("renderSceneConfig", (app, html) => {
  const data = {
    moduleId: MODULE_ID,
    tab: {
      name: MODULE_ID,
      label: "Module"
    },
   foo: {
      type: "checkbox",
      label: "Foo"
      notes: "Bar",
      default: false,
    }
  };
  injectConfig.inject(app, html, data, app.object);
});
```

**Comment by theripper93** [comment]
migrated to internal lib in module template project
